name:
  startername
services:
  mongo:
    image: mongo:8.0
    container_name: startername-mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=startername
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=verysecretpassword
      - MONGO_USER=username
      - MONGO_PASSWORD=password
      - MONGO_DB=startername
    ports:
      - 6060:27017
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
  valkey:
    image: valkey/valkey:8.0-alpine
    container_name: startername-valkey
    restart: unless-stopped
    ports:
      - 6379:6379