name: Pull Request | Web

on:
    pull_request:
        types: [opened, synchronize, reopened]
        paths:
            - ".github/workflows/pull-request-web.yml"
            - "pnpm-lock.yaml"
            - "apps/web/**/*.ts"
            - "apps/web/**/*.tsx"
            - "apps/web/package.json"
            - "apps/web/tsconfig.json"
            - "apps/web/.eslintrc*"

jobs:
    validate:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./apps/web
        strategy:
            matrix:
                pnpm-version: ["10.0.0", "latest"]

        steps:
            - uses: actions/checkout@v4

            - name: Install Node 24.11.1
              uses: actions/setup-node@v4
              with:
                  node-version: 24.11.1

            - name: Setup pnpm ${{ matrix.pnpm-version }}
              uses: pnpm/action-setup@v4
              with:
                  version: ${{ matrix.pnpm-version }}

            - name: Install dependencies (web)
              run: pnpm install

            - name: Build dependencies
              run: pnpm run build:deps
              working-directory: ./

            - name: Type check
              run: pnpm run check-types

            - name: Lint
              run: pnpm run lint

            # - name: Test
            #   run: pnpm run test
            #   env:
            #       CI: true

            - name: Build
              run: pnpm run build
              env:
                  VITE_SERVER_URL: http://localhost:3000
